---
galaxy_info:
  author: Heiko Ritter
  description: Role osism.services.metering
  company: cloudandheat GmbH
  license: Apache License 2.0
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - system
dependencies: []
