---
- name: Git checkout metering
  ansible.builtin.git:
    repo: 'https://github.com/cloudandheat/odoo_openstack_metering.git'
    dest: /srv/checkout/metering
    single_branch: yes
    version: main


- name: Build image
  community.docker.docker_image:
    name: "{{ metering_image }}"
    build:
      path: /srv/checkout/metering
    source: build
